version: '2'
services:
    rorum-app:
        image: rorum
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://rorum-postgresql:5432/RORUM
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8080:8080
    rorum-postgresql:
        extends:
            file: postgresql.yml
            service: rorum-postgresql
